### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by grawlinson** [python-jsonschema/jsonschema-specifications#14]
There is a version string mismatch between the different releases (`PyPi` vs `GitHub`):

PyPi: `2023.7.1`
Git tag: `2023.07.1`

It would be great if the versioning was consistent. :)

**Comment by grawlinson** [comment]
Whoops, mistyped the year. I did mean 2023.07.1.

At the moment, I’m packaging this project for Arch, and the version mismatch means I have to do some additional massaging with sed to [remove the zero](https://gitlab.archlinux.org/archlinux/packaging/packages/python-jsonschema-specifications/-/blob/main/PKGBUILD#L27) from the month.

**Comment by Julian** [comment]
Oh I see -- those two versions are equivalent (`v2023.07.1` and `2023.7.1`) in Python. PyPI is showing a PEP 440 normalized version of the version but `pip install 'jsonschema-specifications==v2023.07.1'` will work exactly the same.

**Comment by grawlinson** [comment]
Ahh okay, thanks for the explanation. Enjoy the rest of your day (or night?).

I'll keep the reference to this issue in that `PKGBUILD`, and revert to using the git tag (minus the `v` prefix).

Note: Thankfully [`vercmp`](https://man.archlinux.org/man/vercmp.8) sees these version strings as equivalent.
