### ISSUE TITLE
To avoid 'taking liberties' in `_schema()`

### ISSUE THREAD

**Issue by paulmromer** [python-jsonschema/jsonschema-specifications#37]
Re your comments in `_schema()`: 

> importlib.resources.abc.Traversal doesn't have nice ways to do this that
> I'm aware of...
> 
> It can't recurse arbitrarily, e.g. no ``.glob()``.
> 
> So this takes some liberties given the real layout of what we ship
> (only 2 levels of nesting, no directories within the second level).

You could use `yield from` together with `yield` in a simple recursive generator function. For example: 

```
def files_in_or_below(p: Path, yield_DS_Store: bool = False):
    """Creates a generator that yields files from
    the subtree of a directory p.

    By default, it excludes the system files named 
    '.DS_Store', which macOS may place in any directory. 
     
    Sample usage:
    
        ```
        for f in files_in_or_below(p):
            print(f.name)
        ```
    
    Acknowledgement: Chap 6 of *Python Distilled* by D. Beazley:
    
        `yield from` is especially useful when writing
        code that must recursively iterate through 
        nested iterables.

    """
    for q in p.iterdir():
        if q.is_dir():
            yield from files_in_or_below(q, yield_DS_Store)
        elif q.is_file() and (not q.name == '.DS_Store' or yield_DS_Store):
            yield q

```

- Just 5 lines.

- Cleaner separation between walking the tree and testing for '.DS_Store'.

- The `yield_DS_Store` argument could of course be dropped. It's there mainly to help people who are not familiar with macOS understand this issue.   

"Quality is the result of a million selfless acts of care." -- James Coplien

**Comment by Julian** [comment]
Thanks for the suggestion -- that code is essentially equivalent to:

```python
def files_in_or_below(p: Path):
    return (
        q
        for child in p.iterdir()
        for q in ([child] if child.is_file() else files_in_or_below(child))
        if q.name != ".DS_Store"
    )

```

Which one one prefers will depend on your appetite for nested comprehensions -- mine tends to be slightly higher than the average. (I've also ignoring the `yield_DS_Store` argument as there's no reason it'd be set to `True` for purposes of this library so it's safe to remove, but it could be treated similarly.)

The above aside -- I of course considered doing something like that, but I'm not really a fan of recursion, particularly in Python, so yet a third solution would really be what I'd have gone with, where you simply don't need to recurse and just iterate until you're done -- but the point though of that comment is that this still is ugly -- `Traversable` should essentially grow that method (and more broadly really the `Path`-like interface needs to be more uniform in my opinion). I've discussed this a time or two with the `importlib-resources` maintainer(s) and they're open to it -- so really above anything that comment is a reminder to myself to simply send a PR at some point adding `.glob`.

Given the above (that really regardless of whether there are improvements to make, what's there is fine and really "internal" to the layout of the package) I'm going to close this, but your suggestion is nonetheless appreciated.
