### ISSUE TITLE
Unable to use jsonschema_specifications on pyoxidizer

### ISSUE THREAD

**Issue by fabioz** [python-jsonschema/jsonschema-specifications#61]
The issue here is that pyoxidizer uses a non-custom importer which is able to get modules to be in-memory (meaning: they are inside the executable and not in the filesystem).

This makes it so that the `jsonschema_specifications._core._schemas()` function when dealing with the code:

```
for version in files(__package__).joinpath("schemas").iterdir():
```

will not really find anything to register.

Usually my approach to this is something as:

As the schemas are always the same in a release, instead of having a bunch of .json files scattered around I'd convert those to python dicts directly and have them as python modules (then the python module can just be imported as usual instead of having the json contents loaded to convert to a python dict).

**Comment by Julian** [comment]
Hi there, please file this with PyOxidizer. Bundlers (obviously out of necessity) do nonstandard things, but there's nothing really to do here as far as I know, it's there where some special casing I believe is occasionally done.

**Comment by fabioz** [comment]
Well, if instead of having scattered files for the configuration those could be python modules for the configuration, things would be much easier on the other side ;)

Any chance you'd accept a PR to do that?

**Comment by Julian** [comment]
The files here are essentially packaging upstream files (from the JSON Schema specifications). I specifically *don't* want to do anything to them so that it's easy to pull in versions as they change upstream (including potentially fixing bugs in old versions).

**Comment by fabioz** [comment]
Humm, what if the code was something as:

```
import json
metadata = json.load('''
<metadata from upstream>
''')
```

Would be that acceptable?

**Comment by Julian** [comment]
Politely (and I do appreciate the offer), no. I don't like sending messages that unsupported environments are supported -- by which I mean -- PyOxidizer does not run in CI here, there's no guarantee it won't break again, (and to be frank at the risk of looking silly given I haven't investigated), I don't really understand why PyOxidizer couldn't make this work in general, many packages make use of importlib.resources in various ways.

**Comment by fabioz** [comment]
Ok, I'll see how to make it work in other ways. Thank you for considering it.

**Comment by fabioz** [comment]
Just to note, for anyone arriving at this bug, the issue created on pyoxidizer is: https://github.com/indygreg/PyOxidizer/issues/749.

My own fix is bundling files with `"filesystem-relative:lib"` in the `pyoxidizer.bzl` file and then doing a hack with:

```
def _iter_jsonschema_specifications():
    from pathlib import Path

    import jsonschema_specifications  # type: ignore
    from referencing import Resource

    parent = Path(jsonschema_specifications._core.__file__).absolute().parent

    for version in (parent / "schemas").iterdir():
        if version.name.startswith("."):
            continue
        for child in version.iterdir():
            children = [child] if child.is_file() else child.iterdir()
            for path in children:
                if path.name.startswith("."):
                    continue
                contents = json.loads(path.read_text(encoding="utf-8"))
                yield Resource.from_contents(contents)


def _fix_jsonschema_specifications():
    import jsonschema_specifications  # type: ignore
    from referencing.jsonschema import EMPTY_REGISTRY as _EMPTY_REGISTRY

    REGISTRY = (_iter_jsonschema_specifications() @ _EMPTY_REGISTRY).crawl()
    jsonschema_specifications.REGISTRY = REGISTRY
```

Off course this library must be pinned because this will break in the future...
